name: invenplus_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  url_launcher: ^6.2.5
  flutter_local_notifications: ^15.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/pharmacy_banner.png
